### ISSUE TITLE
fix:クエリで存在しないidを指定してコンパイルに失敗するとページが固まる

### ISSUE THREAD

**Issue by kiharu3112** [poporonnet/kaniwriter#150]
再現するか確認して欲しいです。
MacのChrome(126.0.6478.127)で確認しました。
kanicc側でこんな感じの表示が出る時です。
```
NotFound: No such file or directory (os error 2): readfile './files/input/d59bf40a-2b74-4a65-9e71-551f3e0e59b2.rb'
    at Object.readFile (ext:deno_fs/30_fs.js:848:24)
    at file:///Users/kiharu/OrbStack/joken/home/kiharu/kanicc/main.ts:126:33
    at dispatch (https://jsr.io/@hono/hono/4.4.6/src/compose.ts:74:23)
    at https://jsr.io/@hono/hono/4.4.6/src/compose.ts:75:20
    at cors (https://jsr.io/@hono/hono/4.4.6/src/middleware/cors/index.ts:139:11)
    at dispatch (https://jsr.io/@hono/hono/4.4.6/src/compose.ts:74:23)
    at https://jsr.io/@hono/hono/4.4.6/src/compose.ts:40:12
    at https://jsr.io/@hono/hono/4.4.6/src/hono-base.ts:443:31
    at Hono.dispatch (https://jsr.io/@hono/hono/4.4.6/src/hono-base.ts:454:6)
    at fetch (https://jsr.io/@hono/hono/4.4.6/src/hono-base.ts:473:17) {
  name: "NotFound",
  code: "ENOENT"
}
```
あと、存在しないidが要求された時には、そう言うエラーを出してもいいかもしれない(もうあったらごめん)。

**Comment by kiharu3112** [comment]
おまかんでした
